export const activities: Activity[] = [
  {
    id: 1,
    name: "Morning Yoga in the Park",
    tags: ["Relaxing", "Health", "Morning"],
    activityLevel: 2,
    image: "26544.jpg",
    hostEmail: "yoga.master@example.com",
    schedule: "Every Saturday at 8:00 AM",
    description: "Join us for a relaxing morning yoga session. All levels welcome.",
  },
  {
    id: 2,
    name: "Advanced Frisbee Techniques",
    tags: ["Sports", "Intense", "Afternoon"],
    activityLevel: 4,
    image: "29893.jpg",
    hostEmail: "frisbee.pro@example.com",
    schedule: "Tuesdays and Thursdays at 4:00 PM",
    description: "Learn advanced frisbee throws and catches. For experienced players.",
  },
  {
    id: 3,
    name: "Historical Walk of Tainan Park",
    tags: ["Educational", "Walking", "Morning"],
    activityLevel: 1,
    image: "29895.jpg",
    hostEmail: "history.buff@example.com",
    schedule: "First Sunday of the month at 9:00 AM",
    description: "A guided tour of the historical monuments and stories of Tainan Park.",
  },
  {
    id: 4,
    name: "Family Picnic Day",
    tags: ["Family", "Relaxing", "All Day"],
    activityLevel: 1,
    image: "34442.jpg",
    hostEmail: "family.fun@example.com",
    schedule: "Next public holiday, all day",
    description: "A fun day out for the whole family. Bring your own food and games.",
  },
  {
    id: 5,
    name: "Outdoor HIIT Workout",
    tags: ["Health", "Intense", "Evening"],
    activityLevel: 5,
    image: "34443.jpg",
    hostEmail: "fitness.guru@example.com",
    schedule: "Mondays and Wednesdays at 6:00 PM",
    description: "A high-intensity interval training workout to get your heart pumping.",
  },
  {
    id: 6,
    name: "Bird Watching Club",
    tags: ["Nature", "Relaxing", "Morning"],
    activityLevel: 1,
    image: "34498.jpg",
    hostEmail: "bird.lover@example.com",
    schedule: "Every other Friday at 7:00 AM",
    description: "Discover the diverse bird species of Tainan Park. Bring binoculars!",
  },
];